version: '3.8'

services:
  xhprof-php-fpm:
    build:
      context: .
      dockerfile: ./docker-configs/php/Dockerfile
    image: xhprof-php:1.0
    container_name: xhprof-php
    volumes:
      - ./httpdocs:/var/www/html
      - ./docker-configs/php/php.ini:/usr/local/etc/php/php.ini

  xhprof-nginx:
    build:
      context: .
      dockerfile: ./docker-configs/nginx/Dockerfile
    image: xhprof-nginx:1.0
    container_name: xhprof-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xhprof-nginx.rule=Host(`test.xhprof.com`)"
      # - "traefik.http.routers.new-strateg-nginx.rule=Host(`test.strateg.ua`)"
      - "traefik.http.routers.xhprof-nginx.entrypoints=web"
    volumes:
      - ./httpdocs:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - xhprof-php-fpm

networks:
  default:
    name: traefik-network
    external: true